javac ./formulaire/*.java
javac ./serveur/Serveur.java
javac ./serveur/Serveur1.java
javac ./serveur/Serveur2.java
javac ./serveur/Serveur3.java
javac ./client/Client.java
java ./serveur/Serveur1.java
java ./serveur/Serveur2.java
java ./serveur/Serveur3.java
java ./serveur/Serveur.java
java ./serveur/Client.java